### ISSUE TITLE
recurr not used

### ISSUE THREAD

**Issue by Dylan-Brotherston** [COMP1511UNSW/blackboard_upload#1]
recurr (int) - the number of times the class will occur 

Isn't used: hardcoded to '10'

**Comment by jashank** [comment]
... and definitely should be set to something other than that --- COMP1521 and COMP2041 won't be running 10 TLBs this term.

**Comment by Dylan-Brotherston** [comment]
@jashank when I manually setup my 1521 classes I just started them in week01 and repeated 10 times and was just going to deal with variance as I went.

The flexible week means that using the recurrenceRule won't work because there is no way to do exceptions. There needs to the at lest two recurrenceRules one before and one after the flexible week.

Holidays just add an extra headache to the mix.

**Comment by Dylan-Brotherston** [comment]
@tfpk Depending on the expected number of interruptions it might be cleaner (in the blackboard interface) if we don't use recurrenceRule at all.

**Comment by tfpk** [comment]
Yep, that's a bug. I'll push a fix now.

I agree holidays and in-flexibility week are headaches, but I think the benefit of the grouping is significant compared to 10 times the number of classes, in terms of students being able to read the interface (and, if memory serves, in terms of accessing recordings).
